<?php

namespace Database\Seeders;

use App\Services\MaterialService;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MasterDataSeeder extends Seeder
{
    public function run(): void
    {
        $rawMaterials = [
            [
                'id' => 1,
                'name' => 'Tepung Terigu',
                'unit' => 'gram',
                'price_per_unit' => 12.0,
                'current_stock' => 0,
                'min_stock_level' => 2000,
            ], // min 2 kg
            [
                'id' => 2,
                'name' => 'Telur Ayam',
                'unit' => 'butir',
                'price_per_unit' => 1800.0,
                'current_stock' => 0,
                'min_stock_level' => 60,
            ], // min 2 tray
            [
                'id' => 3,
                'name' => 'SP (Emulsifier)',
                'unit' => 'gram',
                'price_per_unit' => 80.0,
                'current_stock' => 0,
                'min_stock_level' => 200,
            ], // min 200 gr
            [
                'id' => 4,
                'name' => 'Minyak Goreng',
                'unit' => 'gram',
                'price_per_unit' => 17.0,
                'current_stock' => 0,
                'min_stock_level' => 1000,
            ], // min 1 liter
            [
                'id' => 5,
                'name' => 'Gula Pasir',
                'unit' => 'gram',
                'price_per_unit' => 17.0,
                'current_stock' => 0,
                'min_stock_level' => 2000,
            ], // min 2 kg
            [
                'id' => 6,
                'name' => 'Pewarna Pandan',
                'unit' => 'gram',
                'price_per_unit' => 110.0,
                'current_stock' => 0,
                'min_stock_level' => 100,
            ], // min 100 gr
            [
                'id' => 7,
                'name' => 'Coklat Bubuk',
                'unit' => 'gram',
                'price_per_unit' => 150.0,
                'current_stock' => 0,
                'min_stock_level' => 500,
            ], // min 0.5 kg
            [
                'id' => 8,
                'name' => 'Coklat Batang',
                'unit' => 'gram',
                'price_per_unit' => 60.0,
                'current_stock' => 0,
                'min_stock_level' => 1200,
            ], // min 1,2 kg
            [
                'id' => 9,
                'name' => 'Butter Cream',
                'unit' => 'gram',
                'price_per_unit' => 28.0,
                'current_stock' => 0,
                'min_stock_level' => 1000,
            ], // min 1 kg
            [
                'id' => 10,
                'name' => 'Mentega/Margarin',
                'unit' => 'gram',
                'price_per_unit' => 30.0,
                'current_stock' => 0,
                'min_stock_level' => 500,
            ], // min 0,5 kg
            [
                'id' => 11,
                'name' => 'Tepung Maizena',
                'unit' => 'gram',
                'price_per_unit' => 21.0,
                'current_stock' => 0,
                'min_stock_level' => 400,
            ], // min 0.4 kg
            [
                'id' => 12,
                'name' => 'Susu Bubuk',
                'unit' => 'gram',
                'price_per_unit' => 32.0,
                'current_stock' => 0,
                'min_stock_level' => 300,
            ], // min 0.3 kg
            [
                'id' => 13,
                'name' => 'Selai',
                'unit' => 'gram',
                'price_per_unit' => 24.0,
                'current_stock' => 0,
                'min_stock_level' => 400,
            ], // min 0.3 kg
            [
                'id' => 14,
                'name' => 'Pisang',
                'unit' => 'gram',
                'price_per_unit' => 10.0,
                'current_stock' => 0,
                'min_stock_level' => 1500,
            ], // min 1.5 kg
            [
                'id' => 15,
                'name' => 'Santan Cair',
                'unit' => 'gram',
                'price_per_unit' => 83.0,
                'current_stock' => 0,
                'min_stock_level' => 500,
            ], // min 0,5 liter
            [
                'id' => 16,
                'name' => 'Garam',
                'unit' => 'gram',
                'price_per_unit' => 7.0,
                'current_stock' => 0,
                'min_stock_level' => 200,
            ], // min 1 bks kecil
            [
                'id' => 17,
                'name' => 'Air Lemon',
                'unit' => 'gram',
                'price_per_unit' => 25.0,
                'current_stock' => 0,
                'min_stock_level' => 100,
            ], // min 100 ml
            [
                'id' => 18,
                'name' => 'Parutan Kelapa',
                'unit' => 'gram',
                'price_per_unit' => 18.0,
                'current_stock' => 0,
                'min_stock_level' => 100,
            ], // min 1 kg
            [
                'id' => 19,
                'name' => 'Mika Kue 14',
                'unit' => 'pcs',
                'price_per_unit' => 3000.0,
                'current_stock' => 0,
                'min_stock_level' => 5,
            ], // min 1 bks kecil
            [
                'id' => 20,
                'name' => 'Mika Kue 16',
                'unit' => 'pcs',
                'price_per_unit' => 3200.0,
                'current_stock' => 0,
                'min_stock_level' => 5,
            ], // min 100 ml
            [
                'id' => 21,
                'name' => 'Mika Kue 18',
                'unit' => 'pcs',
                'price_per_unit' => 3500.0,
                'current_stock' => 0,
                'min_stock_level' => 5,
            ], // min 1 kg
            [
                'id' => 22,
                'name' => 'Mika Kue 20',
                'unit' => 'pcs',
                'price_per_unit' => 5000.0,
                'current_stock' => 0,
                'min_stock_level' => 5,
            ], // min 1 bks kecil
            [
                'id' => 23,
                'name' => 'Mika Kue 22',
                'unit' => 'pcs',
                'price_per_unit' => 6500.0,
                'current_stock' => 0,
                'min_stock_level' => 5,
            ], // min 100 ml
            [
                'id' => 24,
                'name' => 'Mika Kue 24',
                'unit' => 'pcs',
                'price_per_unit' => 8000.0,
                'current_stock' => 0,
                'min_stock_level' => 5,
            ], // min 1 bks kecil
            [
                'id' => 25,
                'name' => 'Kardus Kue 16',
                'unit' => 'pcs',
                'price_per_unit' => 15000.0,
                'current_stock' => 0,
                'min_stock_level' => 5,
            ], // min 100 ml
            [
                'id' => 26,
                'name' => 'Kardus Kue 24',
                'unit' => 'pcs',
                'price_per_unit' => 2500.0,
                'current_stock' => 0,
                'min_stock_level' => 5,
            ], // min 1 kg
            [
                'id' => 27,
                'name' => 'Plastik',
                'unit' => 'pcs',
                'price_per_unit' => 18.0,
                'current_stock' => 0,
                'min_stock_level' => 50,
            ], // min 1 kg
        ];

        // Konversi ke base unit (kg / liter) langsung di PHP
        // price_per_unit: harga per unit kecil (gram / ml)
        // price_per_base_unit: harga per base unit (kg / liter / dll)
        $now = now();

        $materials = array_map(function (array $row) use ($now) {
            $pricePerUnit = (float) $row['price_per_unit'];
            $conversion = MaterialService::convertUnitPricing($row['unit'], $pricePerUnit);

            return [
                'id' => $row['id'],
                'name' => $row['name'],
                'unit' => $row['unit'],
                'base_unit' => $conversion['base_unit'],
                'price_per_unit' => $pricePerUnit,
                'price_per_base_unit' => $conversion['price_per_base_unit'],
                'current_stock' => $row['current_stock'],
                'min_stock_level' => $row['min_stock_level'],
                'created_at' => $now,
                'updated_at' => $now,
            ];
        }, $rawMaterials);

        DB::table('materials')->insert($materials);

        DB::table('products')->insert([
            [
                'id' => 1,
                'name' => 'Kue Tart Bolu 14',
                'selling_price' => 50000,
                'overhead_cost_per_unit' => 0,
                'description' => 'Kue Tart Bolu 14',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'name' => 'Kue Tart Bolu 16',
                'selling_price' => 60000,
                'overhead_cost_per_unit' => 0,
                'description' => 'Kue Tart Bolu 16',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'name' => 'Kue Tart Bolu 18',
                'selling_price' => 70000,
                'overhead_cost_per_unit' => 0,
                'description' => 'Kue Tart Bolu 18',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'name' => 'Kue Tart Bolu 20',
                'selling_price' => 80000,
                'overhead_cost_per_unit' => 0,
                'description' => 'Kue Tart Bolu 20',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'name' => 'Kue Tart Bolu 22',
                'selling_price' => 90000,
                'overhead_cost_per_unit' => 0,
                'description' => 'Kue Tart Bolu 22',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'name' => 'Kue Tart Bolu 24',
                'selling_price' => 100000,
                'overhead_cost_per_unit' => 0,
                'description' => 'Kue Tart Bolu 24',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'name' => 'Kue Tart Brownies 14',
                'selling_price' => 60000,
                'overhead_cost_per_unit' => 0,
                'description' => 'Kue Tart Brownies 14',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'name' => 'Kue Tart Brownies 16',
                'selling_price' => 75000,
                'overhead_cost_per_unit' => 0,
                'description' => 'Kue Tart Brownies 16',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'name' => 'Kue Tart Brownies 18',
                'selling_price' => 100000,
                'overhead_cost_per_unit' => 0,
                'description' => 'Kue Tart Brownies 18',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'name' => 'Kue Tart Brownies 20',
                'selling_price' => 120000,
                'overhead_cost_per_unit' => 0,
                'description' => 'Kue Tart Brownies 20',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'name' => 'Kue Tart Brownies 22',
                'selling_price' => 135000,
                'overhead_cost_per_unit' => 0,
                'description' => 'Kue Tart Brownies 22',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'name' => 'Kue Tart Brownies 24',
                'selling_price' => 155000,
                'overhead_cost_per_unit' => 0,
                'description' => 'Kue Tart Brownies 24',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 13,
                'name' => 'Bolu Gulung (12 biji)',
                'selling_price' => 35000,
                'overhead_cost_per_unit' => 0,
                'description' => 'Kue Bolu Gulung (12 biji)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 14,
                'name' => 'Bolu Pisang 18',
                'selling_price' => 55000,
                'overhead_cost_per_unit' => 0,
                'description' => 'Kue Bolu Pisang 18',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 15,
                'name' => 'Brownis Kukus 24 (30 biji)',
                'selling_price' => 105000,
                'overhead_cost_per_unit' => 0,
                'description' => 'Kue Brownis Kukus 24 (30 biji)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 16,
                'name' => 'Brownis Panggang (15 biji)',
                'selling_price' => 75000,
                'overhead_cost_per_unit' => 0,
                'description' => 'Kue Brownis Panggang (15 biji)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 17,
                'name' => 'Bolen pisang (40 biji)',
                'selling_price' => 100000,
                'overhead_cost_per_unit' => 0,
                'description' => 'Kue Bolen pisang (40 biji)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 18,
                'name' => 'bolu jadul (24 biji)',
                'selling_price' => 65000,
                'overhead_cost_per_unit' => 0,
                'description' => 'Kue bolu jadul (24 biji)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 19,
                'name' => 'Shifon cake (16 biji)',
                'selling_price' => 56000,
                'overhead_cost_per_unit' => 0,
                'description' => 'Kue Shifon cake (16 biji)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 20,
                'name' => 'Bolu Kukus biasa (24 biji)',
                'selling_price' => 60000,
                'overhead_cost_per_unit' => 0,
                'description' => 'Kue Bolu Kukus biasa (24 biji)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 21,
                'name' => 'Putu ayu (25 biji)',
                'selling_price' => 75000,
                'overhead_cost_per_unit' => 0,
                'description' => 'Kue Putu ayu (25 biji)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        DB::table('product_materials')->insert([
            ['product_id' => 1, 'material_id' => 1, 'quantity_needed' => 120.0],
            ['product_id' => 1, 'material_id' => 2, 'quantity_needed' => 2.0],
            ['product_id' => 1, 'material_id' => 3, 'quantity_needed' => 2.0],
            ['product_id' => 1, 'material_id' => 4, 'quantity_needed' => 60.0],
            ['product_id' => 1, 'material_id' => 5, 'quantity_needed' => 90.0],
            ['product_id' => 1, 'material_id' => 6, 'quantity_needed' => 2.0],
            ['product_id' => 1, 'material_id' => 9, 'quantity_needed' => 250.0],
            ['product_id' => 1, 'material_id' => 19, 'quantity_needed' => 1.0],
            ['product_id' => 2, 'material_id' => 1, 'quantity_needed' => 180.0],
            ['product_id' => 2, 'material_id' => 2, 'quantity_needed' => 3.0],
            ['product_id' => 2, 'material_id' => 3, 'quantity_needed' => 2.0],
            ['product_id' => 2, 'material_id' => 4, 'quantity_needed' => 90.0],
            ['product_id' => 2, 'material_id' => 5, 'quantity_needed' => 135.0],
            ['product_id' => 2, 'material_id' => 6, 'quantity_needed' => 3.0],
            ['product_id' => 2, 'material_id' => 9, 'quantity_needed' => 350.0],
            ['product_id' => 2, 'material_id' => 20, 'quantity_needed' => 1.0],
            ['product_id' => 3, 'material_id' => 1, 'quantity_needed' => 240.0],
            ['product_id' => 3, 'material_id' => 2, 'quantity_needed' => 4.0],
            ['product_id' => 3, 'material_id' => 3, 'quantity_needed' => 3.0],
            ['product_id' => 3, 'material_id' => 4, 'quantity_needed' => 120.0],
            ['product_id' => 3, 'material_id' => 5, 'quantity_needed' => 180.0],
            ['product_id' => 3, 'material_id' => 6, 'quantity_needed' => 4.0],
            ['product_id' => 3, 'material_id' => 9, 'quantity_needed' => 450.0],
            ['product_id' => 3, 'material_id' => 21, 'quantity_needed' => 1.0],
            ['product_id' => 4, 'material_id' => 1, 'quantity_needed' => 300.0],
            ['product_id' => 4, 'material_id' => 2, 'quantity_needed' => 5.0],
            ['product_id' => 4, 'material_id' => 3, 'quantity_needed' => 3.0],
            ['product_id' => 4, 'material_id' => 4, 'quantity_needed' => 120.0],
            ['product_id' => 4, 'material_id' => 5, 'quantity_needed' => 225.0],
            ['product_id' => 4, 'material_id' => 6, 'quantity_needed' => 5.0],
            ['product_id' => 4, 'material_id' => 9, 'quantity_needed' => 550.0],
            ['product_id' => 4, 'material_id' => 22, 'quantity_needed' => 1.0],
            ['product_id' => 5, 'material_id' => 1, 'quantity_needed' => 360.0],
            ['product_id' => 5, 'material_id' => 2, 'quantity_needed' => 6.0],
            ['product_id' => 5, 'material_id' => 3, 'quantity_needed' => 4.0],
            ['product_id' => 5, 'material_id' => 4, 'quantity_needed' => 150.0],
            ['product_id' => 5, 'material_id' => 5, 'quantity_needed' => 270.0],
            ['product_id' => 5, 'material_id' => 6, 'quantity_needed' => 6.0],
            ['product_id' => 5, 'material_id' => 9, 'quantity_needed' => 650.0],
            ['product_id' => 5, 'material_id' => 23, 'quantity_needed' => 1.0],
            ['product_id' => 6, 'material_id' => 1, 'quantity_needed' => 420.0],
            ['product_id' => 6, 'material_id' => 2, 'quantity_needed' => 7.0],
            ['product_id' => 6, 'material_id' => 3, 'quantity_needed' => 4.0],
            ['product_id' => 6, 'material_id' => 4, 'quantity_needed' => 150.0],
            ['product_id' => 6, 'material_id' => 5, 'quantity_needed' => 315.0],
            ['product_id' => 6, 'material_id' => 6, 'quantity_needed' => 7.0],
            ['product_id' => 6, 'material_id' => 9, 'quantity_needed' => 750.0],
            ['product_id' => 6, 'material_id' => 24, 'quantity_needed' => 1.0],
            ['product_id' => 7, 'material_id' => 1, 'quantity_needed' => 45.0],
            ['product_id' => 7, 'material_id' => 2, 'quantity_needed' => 2.0],
            ['product_id' => 7, 'material_id' => 3, 'quantity_needed' => 2.0],
            ['product_id' => 7, 'material_id' => 4, 'quantity_needed' => 60.0],
            ['product_id' => 7, 'material_id' => 5, 'quantity_needed' => 75.0],
            ['product_id' => 7, 'material_id' => 6, 'quantity_needed' => 2.0],
            ['product_id' => 7, 'material_id' => 7, 'quantity_needed' => 15.0],
            ['product_id' => 7, 'material_id' => 8, 'quantity_needed' => 35.0],
            ['product_id' => 7, 'material_id' => 9, 'quantity_needed' => 250.0],
            ['product_id' => 7, 'material_id' => 19, 'quantity_needed' => 1.0],
            ['product_id' => 8, 'material_id' => 1, 'quantity_needed' => 70.0],
            ['product_id' => 8, 'material_id' => 2, 'quantity_needed' => 3.0],
            ['product_id' => 8, 'material_id' => 3, 'quantity_needed' => 2.0],
            ['product_id' => 8, 'material_id' => 4, 'quantity_needed' => 60.0],
            ['product_id' => 8, 'material_id' => 5, 'quantity_needed' => 110.0],
            ['product_id' => 8, 'material_id' => 6, 'quantity_needed' => 3.0],
            ['product_id' => 8, 'material_id' => 7, 'quantity_needed' => 22.0],
            ['product_id' => 8, 'material_id' => 8, 'quantity_needed' => 52.0],
            ['product_id' => 8, 'material_id' => 9, 'quantity_needed' => 350.0],
            ['product_id' => 8, 'material_id' => 20, 'quantity_needed' => 1.0],
            ['product_id' => 9, 'material_id' => 1, 'quantity_needed' => 95.0],
            ['product_id' => 9, 'material_id' => 2, 'quantity_needed' => 4.0],
            ['product_id' => 9, 'material_id' => 3, 'quantity_needed' => 3.0],
            ['product_id' => 9, 'material_id' => 4, 'quantity_needed' => 120.0],
            ['product_id' => 9, 'material_id' => 5, 'quantity_needed' => 145.0],
            ['product_id' => 9, 'material_id' => 6, 'quantity_needed' => 4.0],
            ['product_id' => 9, 'material_id' => 7, 'quantity_needed' => 29.0],
            ['product_id' => 9, 'material_id' => 8, 'quantity_needed' => 69.0],
            ['product_id' => 9, 'material_id' => 9, 'quantity_needed' => 450.0],
            ['product_id' => 9, 'material_id' => 21, 'quantity_needed' => 1.0],
            ['product_id' => 10, 'material_id' => 1, 'quantity_needed' => 120.0],
            ['product_id' => 10, 'material_id' => 2, 'quantity_needed' => 5.0],
            ['product_id' => 10, 'material_id' => 3, 'quantity_needed' => 3.0],
            ['product_id' => 10, 'material_id' => 4, 'quantity_needed' => 120.0],
            ['product_id' => 10, 'material_id' => 5, 'quantity_needed' => 180.0],
            ['product_id' => 10, 'material_id' => 6, 'quantity_needed' => 5.0],
            ['product_id' => 10, 'material_id' => 7, 'quantity_needed' => 36.0],
            ['product_id' => 10, 'material_id' => 8, 'quantity_needed' => 86.0],
            ['product_id' => 10, 'material_id' => 9, 'quantity_needed' => 550.0],
            ['product_id' => 10, 'material_id' => 22, 'quantity_needed' => 1.0],
            ['product_id' => 11, 'material_id' => 1, 'quantity_needed' => 145.0],
            ['product_id' => 11, 'material_id' => 2, 'quantity_needed' => 6.0],
            ['product_id' => 11, 'material_id' => 3, 'quantity_needed' => 4.0],
            ['product_id' => 11, 'material_id' => 4, 'quantity_needed' => 150.0],
            ['product_id' => 11, 'material_id' => 5, 'quantity_needed' => 215.0],
            ['product_id' => 11, 'material_id' => 6, 'quantity_needed' => 6.0],
            ['product_id' => 11, 'material_id' => 7, 'quantity_needed' => 43.0],
            ['product_id' => 11, 'material_id' => 8, 'quantity_needed' => 103.0],
            ['product_id' => 11, 'material_id' => 9, 'quantity_needed' => 650.0],
            ['product_id' => 11, 'material_id' => 23, 'quantity_needed' => 1.0],
            ['product_id' => 12, 'material_id' => 1, 'quantity_needed' => 170.0],
            ['product_id' => 12, 'material_id' => 2, 'quantity_needed' => 7.0],
            ['product_id' => 12, 'material_id' => 3, 'quantity_needed' => 4.0],
            ['product_id' => 12, 'material_id' => 4, 'quantity_needed' => 150.0],
            ['product_id' => 12, 'material_id' => 5, 'quantity_needed' => 250.0],
            ['product_id' => 12, 'material_id' => 6, 'quantity_needed' => 7.0],
            ['product_id' => 12, 'material_id' => 7, 'quantity_needed' => 50.0],
            ['product_id' => 12, 'material_id' => 8, 'quantity_needed' => 120.0],
            ['product_id' => 12, 'material_id' => 9, 'quantity_needed' => 750.0],
            ['product_id' => 12, 'material_id' => 24, 'quantity_needed' => 1.0],
            ['product_id' => 13, 'material_id' => 1, 'quantity_needed' => 70.0],
            ['product_id' => 13, 'material_id' => 2, 'quantity_needed' => 6.0],
            ['product_id' => 13, 'material_id' => 3, 'quantity_needed' => 3.0],
            ['product_id' => 13, 'material_id' => 5, 'quantity_needed' => 90.0],
            ['product_id' => 13, 'material_id' => 10, 'quantity_needed' => 125.0],
            ['product_id' => 13, 'material_id' => 11, 'quantity_needed' => 15.0],
            ['product_id' => 13, 'material_id' => 12, 'quantity_needed' => 10.0],
            ['product_id' => 13, 'material_id' => 13, 'quantity_needed' => 100.0],
            ['product_id' => 13, 'material_id' => 27, 'quantity_needed' => 12.0],
            ['product_id' => 14, 'material_id' => 1, 'quantity_needed' => 350.0],
            ['product_id' => 14, 'material_id' => 2, 'quantity_needed' => 6.0],
            ['product_id' => 14, 'material_id' => 3, 'quantity_needed' => 4.0],
            ['product_id' => 14, 'material_id' => 4, 'quantity_needed' => 200.0],
            ['product_id' => 14, 'material_id' => 5, 'quantity_needed' => 300.0],
            ['product_id' => 14, 'material_id' => 14, 'quantity_needed' => 370.0],
            ['product_id' => 14, 'material_id' => 26, 'quantity_needed' => 1.0],
            ['product_id' => 15, 'material_id' => 1, 'quantity_needed' => 170.0],
            ['product_id' => 15, 'material_id' => 2, 'quantity_needed' => 7.0],
            ['product_id' => 15, 'material_id' => 3, 'quantity_needed' => 4.0],
            ['product_id' => 15, 'material_id' => 4, 'quantity_needed' => 150.0],
            ['product_id' => 15, 'material_id' => 5, 'quantity_needed' => 250.0],
            ['product_id' => 15, 'material_id' => 7, 'quantity_needed' => 50.0],
            ['product_id' => 15, 'material_id' => 8, 'quantity_needed' => 120.0],
            ['product_id' => 15, 'material_id' => 27, 'quantity_needed' => 30.0],
            ['product_id' => 16, 'material_id' => 1, 'quantity_needed' => 200.0],
            ['product_id' => 16, 'material_id' => 2, 'quantity_needed' => 4.0],
            ['product_id' => 16, 'material_id' => 4, 'quantity_needed' => 80.0],
            ['product_id' => 16, 'material_id' => 5, 'quantity_needed' => 170.0],
            ['product_id' => 16, 'material_id' => 7, 'quantity_needed' => 70.0],
            ['product_id' => 16, 'material_id' => 8, 'quantity_needed' => 300.0],
            ['product_id' => 16, 'material_id' => 10, 'quantity_needed' => 100.0],
            ['product_id' => 16, 'material_id' => 27, 'quantity_needed' => 15.0],
            ['product_id' => 17, 'material_id' => 1, 'quantity_needed' => 740.0],
            ['product_id' => 17, 'material_id' => 2, 'quantity_needed' => 2.0],
            ['product_id' => 17, 'material_id' => 4, 'quantity_needed' => 20.0],
            ['product_id' => 17, 'material_id' => 5, 'quantity_needed' => 150.0],
            ['product_id' => 17, 'material_id' => 10, 'quantity_needed' => 180.0],
            ['product_id' => 17, 'material_id' => 27, 'quantity_needed' => 40.0],
            ['product_id' => 18, 'material_id' => 1, 'quantity_needed' => 420.0],
            ['product_id' => 18, 'material_id' => 2, 'quantity_needed' => 7.0],
            ['product_id' => 18, 'material_id' => 3, 'quantity_needed' => 4.0],
            ['product_id' => 18, 'material_id' => 4, 'quantity_needed' => 150.0],
            ['product_id' => 18, 'material_id' => 5, 'quantity_needed' => 315.0],
            ['product_id' => 18, 'material_id' => 6, 'quantity_needed' => 7.0],
            ['product_id' => 18, 'material_id' => 27, 'quantity_needed' => 24.0],
            ['product_id' => 19, 'material_id' => 1, 'quantity_needed' => 140.0],
            ['product_id' => 19, 'material_id' => 2, 'quantity_needed' => 6.0],
            ['product_id' => 19, 'material_id' => 4, 'quantity_needed' => 80.0],
            ['product_id' => 19, 'material_id' => 5, 'quantity_needed' => 160.0],
            ['product_id' => 19, 'material_id' => 15, 'quantity_needed' => 120.0],
            ['product_id' => 19, 'material_id' => 16, 'quantity_needed' => 2.0],
            ['product_id' => 19, 'material_id' => 17, 'quantity_needed' => 2.0],
            ['product_id' => 19, 'material_id' => 27, 'quantity_needed' => 16.0],
            ['product_id' => 20, 'material_id' => 1, 'quantity_needed' => 420.0],
            ['product_id' => 20, 'material_id' => 2, 'quantity_needed' => 8.0],
            ['product_id' => 20, 'material_id' => 3, 'quantity_needed' => 4.0],
            ['product_id' => 20, 'material_id' => 4, 'quantity_needed' => 150.0],
            ['product_id' => 20, 'material_id' => 5, 'quantity_needed' => 315.0],
            ['product_id' => 20, 'material_id' => 15, 'quantity_needed' => 120.0],
            ['product_id' => 20, 'material_id' => 16, 'quantity_needed' => 2.0],
            ['product_id' => 20, 'material_id' => 27, 'quantity_needed' => 24.0],
            ['product_id' => 21, 'material_id' => 1, 'quantity_needed' => 500.0],
            ['product_id' => 21, 'material_id' => 2, 'quantity_needed' => 6.0],
            ['product_id' => 21, 'material_id' => 3, 'quantity_needed' => 8.0],
            ['product_id' => 21, 'material_id' => 5, 'quantity_needed' => 45.0],
            ['product_id' => 21, 'material_id' => 11, 'quantity_needed' => 20.0],
            ['product_id' => 21, 'material_id' => 15, 'quantity_needed' => 300.0],
            ['product_id' => 21, 'material_id' => 16, 'quantity_needed' => 3.0],
            ['product_id' => 21, 'material_id' => 18, 'quantity_needed' => 40.0],
            ['product_id' => 21, 'material_id' => 27, 'quantity_needed' => 25.0],
        ]);
    }
}
